name: run_db_cli

on:
  workflow_dispatch:
    # schedule:
    #   - cron: "0 3 * * *" # every day at 3h

# https://stackoverflow.com/questions/57806624/github-actions-how-to-build-project-in-sub-directory
defaults:
  run:
    working-directory: db_cli

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: db_cli/yarn.lock
      - run: node --version
      - run: yarn --version
      - run: yarn install --frozen-lockfile
      - run: yarn start --all
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PWD: ${{ secrets.DB_PWD }}
          DB_NAME: ${{ secrets.DB_NAME }}
